
import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import java.awt.event.WindowEvent;
import static java.lang.System.exit;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vladimirg
 */
public class XOJFrame extends javax.swing.JFrame {

    boolean igrac1 = false;
    boolean igrac2 = false;
    char c1 = '0';
    char c2 = '0';
    char c3 = '0';
    char c4 = '0';
    char c5 = '0';
    char c6 = '0';
    char c7 = '0';
    char c8 = '0';
    char c9 = '0';

    /**
     * Creates new form NewJFrame
     */
    public XOJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        jDialog1.setTitle("Prvi igrač je pobedio, nova partija?");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XO Game");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Prvi igrač");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Drugi igrač");

        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        igrac1 = true;
        jButton2.setVisible(true);
        jButton2.setForeground(Color.BLUE);
        jButton3.setVisible(false);
        jButton3.setForeground(Color.BLUE);
        jButton3.setEnabled(false);
        jButton3.setEnabled(false);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);
        jButton13.setEnabled(true);
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        jButton10.setText("");
        jButton11.setText("");
        jButton12.setText("");
        jButton13.setText("");

        jButton1.setEnabled(false);
        c1 = '0';
        c2 = '0';
        c3 = '0';
        c4 = '0';
        c5 = '0';
        c6 = '0';
        c7 = '0';
        c8 = '0';
        c9 = '0';

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (igrac1) {
            jButton5.setText("X");
            jButton5.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            jButton3.setForeground(Color.BLUE);
            igrac1 = false;
            igrac2 = true;
            c1 = 'X';
            provera();
        } else {
            jButton5.setText("O");
            jButton5.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c1 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (igrac1) {
            jButton6.setText("X");
            jButton6.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c2 = 'X';
            provera();
        } else {
            jButton6.setText("O");
            jButton6.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c2 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (igrac1) {
            jButton7.setText("X");
            jButton7.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c3 = 'X';
            provera();
        } else {
            jButton7.setText("O");
            jButton7.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c3 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (igrac1) {
            jButton8.setText("X");
            jButton8.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c4 = 'X';
            provera();
        } else {
            jButton8.setText("O");
            jButton8.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c4 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (igrac1) {
            jButton9.setText("X");
            jButton9.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c5 = 'X';
            provera();
        } else {
            jButton9.setText("O");
            jButton9.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c5 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (igrac1) {
            jButton10.setText("X");
            jButton10.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c6 = 'X';
            provera();
        } else {
            jButton10.setText("O");
            jButton10.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c6 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (igrac1) {
            jButton11.setText("X");
            jButton11.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c7 = 'X';
            provera();
        } else {
            jButton11.setText("O");
            jButton11.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c7 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (igrac1) {
            jButton12.setText("X");
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            jButton3.setForeground(Color.BLUE);
            igrac1 = false;
            igrac2 = true;
            c8 = 'X';
            provera();
        } else {
            jButton12.setText("O");
            jButton12.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c8 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (igrac1) {
            jButton13.setText("X");
            jButton13.setEnabled(false);
            jButton2.setVisible(false);
            jButton3.setVisible(true);
            igrac1 = false;
            igrac2 = true;
            c9 = 'X';
            provera();
        } else {
            jButton13.setText("O");
            jButton13.setEnabled(false);
            jButton2.setVisible(true);
            jButton3.setVisible(false);
            igrac1 = true;
            igrac2 = false;
            c9 = 'O';
            provera();
        }
    }//GEN-LAST:event_jButton13ActionPerformed
    void provera() {
        if ((c1 == 'X' && c2 == 'X' && c3 == 'X') || (c1 == 'X' && c4 == 'X' && c7 == 'X') || (c1 == 'X' && c5 == 'X' && c9 == 'X') || (c2 == 'X' && c5 == 'X' && c8 == 'X') || (c3 == 'X' && c6 == 'X' && c9 == 'X') || (c4 == 'X' && c5 == 'X' && c6 == 'X') || (c7 == 'X' && c8 == 'X' && c9 == 'X') || (c3 == 'X' && c5 == 'X' && c7 == 'X')) {
            Component frame = null;

            int n = JOptionPane.showConfirmDialog(
                    frame,
                    "Pobedio je prvi igrač. Da li želite novu partiju?",
                    "Odlučivanje",
                    JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                jButton1.setEnabled(true);
                start();
            } else {
                System.exit(0);
            }

        } else if ((c1 == 'O' && c2 == 'O' && c3 == 'O') || (c1 == 'O' && c4 == 'O' && c7 == 'O') || (c1 == 'O' && c5 == 'O' && c9 == 'O') || (c2 == 'O' && c5 == 'O' && c8 == 'O') || (c3 == 'O' && c6 == 'O' && c9 == 'O') || (c4 == 'O' && c5 == 'O' && c6 == 'O') || (c7 == 'O' && c8 == 'O' && c9 == 'O') || (c3 == 'O' && c5 == 'O' && c7 == 'O')) {
            Component frame = null;

            int n = JOptionPane.showConfirmDialog(
                    frame,
                    "Pobedio je drugi igrač. Da li želite novu partiju?",
                    "Odlučivanje",
                    JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                jButton1.setEnabled(true);
                start();
            } else {
                System.exit(0);
            }

        } else if (c1 != '0' && c2 != '0' && c3 != '0' && c4 != '0' && c5 != '0' && c6 != '0' && c7 != '0' && c8 != '0' && c9 != '0') {
            Component frame = null;

            int n = JOptionPane.showConfirmDialog(
                    frame,
                    "Rezultat je nerešen. Da li želite novu partiju?",
                    "Odlučivanje",
                    JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                jButton1.setEnabled(true);
                start();
            } else {
                System.exit(0);
            }
        }
    }

    void start() {
        igrac1 = true;
        jButton2.setVisible(false);
        jButton3.setVisible(false);

        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        jButton11.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        jButton10.setText("");
        jButton11.setText("");
        jButton12.setText("");
        jButton13.setText("");

        c1 = '0';
        c2 = '0';
        c3 = '0';
        c4 = '0';
        c5 = '0';
        c6 = '0';
        c7 = '0';
        c8 = '0';
        c9 = '0';
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XOJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XOJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
}
